[versions]
kotlin = "2.0.0"
resources = "0.4.1"
benchmark = "0.4.10"

[libraries]
resources = { module = "com.goncalossilva:resources", version.ref = "resources" }
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
kotlinx-benchmark = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "benchmark" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "benchmark" }
publish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
resources = { id = "com.goncalossilva.resources", version.ref = "resources" }