# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Gradle task check
        run: ./gradlew check --continue

      - name: Coverage Report
        id: kover
        uses: mi-kas/kover-report@v1.9
        if: success() || failure()
        with:
          path: |
            ${{ github.workspace }}/turf/build/reports/kover/report.xml
            ${{ github.workspace }}/geojson/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-changed-files: 80
          coverage-counter-type: LINE

      - name: detekt report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        if: success() || failure()
        with:
          path: '**/build/reports/detekt/detekt.xml'
          title: "detekt Report"

      - name: ktlint report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        if: success() || failure()
        with:
          path: '**/build/reports/ktlint/ktlint*/ktlint*.xml'
          title: "ktlint Report"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/*Test/TEST-*.xml'
          check_name: 'Test Report'
